name: 'build and deploy Speckle functions'
on:
  push:
    branches:
      - main

jobs:
  publish-automate-function-version: # make sure the action works on a clean machine without building
    env:
      FUNCTION_SCHEMA_PATH: ${HOME}/functionSchema.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.x
          cache: true

      - name: Restore dependencies
        run: dotnet restore --locked-mode
      - name: Extract functionInputSchema
        id: extract_schema
        run: |
          dotnet build
          echo $(dotnet run generate-schema) > functionSchema.json
          cat functionSchema.json
      - name: Speckle Automate Function - Build and Publish
        uses: specklesystems/speckle-automate-github-composite-action@0.3.1
        with:
          speckle_automate_url: 'https://automate.speckle.dev'
          speckle_token: ${{ secrets.SPECKLE_FUNCTION_TOKEN }}
          speckle_function_id: ${{ secrets.SPECKLE_FUNCTION_ID }}
          speckle_function_input_schema_file_path: functionSchema.json
          speckle_function_command: 'dotnet SpeckleAutomateDotnetExample.dll'
